In [1]:
from src import *

In [2]:
form = {
    Generic('{}.json', DataTypes.IMAGE_SET): JSONFile({
        'images': GenericList([{
            'id': DataTypes.IMAGE_ID,
            'file_name': Generic('{}.jpg', DataTypes.IMAGE_NAME)
        }]),
        'categories': GenericList([{
            'id': DataTypes.BBOX_CLASS_ID,
            'name': DataTypes.BBOX_CLASS_NAME
        }]),
        'annotations': GenericList([{
            'image_id': DataTypes.IMAGE_ID,
            'category_id': DataTypes.BBOX_CLASS_ID,
            'bbox': GenericList([
                DataTypes.XMIN, DataTypes.YMIN, DataTypes.XMAX, DataTypes.YMAX
            ])
        }])
    }),
    'images': {
        Generic('{}.jpg', DataTypes.IMAGE_NAME): Image()
    }
}
dataset = CVData('/Users/atong/Documents/Datasets/Avo', form)

In [3]:
dataset.dataframe

IMAGE_NAME  \
0         picam2-wideangle-RGB2023-Apr-15-17-29-20   
1         picam2-wideangle-RGB2023-Apr-15-17-34-52   
2         picam2-wideangle-RGB2023-Apr-15-17-30-24   
3         picam2-wideangle-RGB2023-Apr-15-17-29-08   
4    picam2-wideangle-RGB-2023-Mar-04-22-47-43-106   
..                                             ...   
540       picam2-wideangle-RGB2023-Apr-15-17-32-29   
541       picam2-wideangle-RGB2023-Apr-15-17-29-41   
542       picam2-wideangle-RGB2023-Apr-15-17-25-53   
543       picam2-wideangle-RGB2023-Apr-15-17-29-14   
544       picam2-wideangle-RGB2023-Apr-15-17-33-19   

                                         ABSOLUTE_FILE  IMAGE_ID  \
0    /Users/atong/Documents/Datasets/Avo/images/pic...     847.0   
1    /Users/atong/Documents/Datasets/Avo/images/pic...    1480.0   
2    /Users/atong/Documents/Datasets/Avo/images/pic...     963.0   
3    /Users/atong/Documents/Datasets/Avo/images/pic...     811.0   
4    /Users/atong/Documents/Datasets/Avo/images/pic...      85.0   
..                                                 ...       ...   
540  /Users/atong/Documents/Datasets/Avo/images/pic...    1230.0   
541  /Users/atong/Documents/Datasets/Avo/images/pic...     881.0   
542  /Users/atong/Documents/Datasets/Avo/images/pic...     390.0   
543  /Users/atong/Documents/Datasets/Avo/images/pic...     829.0   
544  /Users/atong/Documents/Datasets/Avo/images/pic...    1322.0   

                                         BBOX_CLASS_ID  \
0    [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...   
1              [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]   
2                    [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0]   
3    [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...   
4                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]   
..                                                 ...   
540  [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...   
541                                             [0, 0]   
542  [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...   
543                        [3, 3, 3, 3, 3, 3, 3, 3, 0]   
544  [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...   

                                                  XMIN  \
0    [273.41488224340276, 423.3131119955788, 333.90...   
1    [132.9231717042449, 15.337355654737184, 134.62...   
2    [227.3684210526316, 211.12781954887222, 327.13...   
3    [1331.310121288145, 1403.9493966648797, 1367.6...   
4    [1268.4953827331424, 437.0689409913666, 1029.4...   
..                                                 ...   
540  [704.2080100021899, 635.6360649509456, 666.405...   
541           [174.13624835783673, 414.92168766107056]   
542  [225.59348832441748, 598.4581559819228, 475.58...   
543  [393.85351593182764, 557.3712310540249, 619.78...   
544  [905.9950885097803, 847.9914070891516, 933.834...   

                                                  YMIN  \
0    [412.86635910363765, 326.2478345368859, 330.43...   
1    [804.3605467808779, 427.74516216549296, 35.791...   
2    [419.93555316863586, 527.8195488721805, 509.25...   
3    [117.29897801576465, 237.8263682704953, 0.9783...   
4    [451.56885846501393, 352.14085293143273, 337.6...   
..                                                 ...   
540  [603.7367437976304, 514.9448662312761, 739.122...   
541           [135.23156089193816, 12.280040632789287]   
542  [686.6938484547085, 727.576816230281, 562.4806...   
543  [210.11147265701672, 181.97939263599355, 170.5...   
544  [270.2900107411386, 255.20945220193343, 214.60...   

                                                  XMAX  \
0    [73.25162701431297, 67.05950289038883, 57.2799...   
1    [102.24834838066283, 69.86960707346181, 110.76...   
2    [51.04189044038668, 60.32223415682062, 51.0418...   
3    [54.883008062422185, 35.51253462862614, 51.361...   
4    [352.14085293143273, 252.71284739785176, 171.9...   
..                                                 ...   
540  [57.14328754270336, 50.98939503810444, 51.8685...   
541            [161

In [4]:
CVData._detection_cols.issubset(dataset.dataframe.columns)

True

In [3]:
dataloader = dataset.get_dataloader('detection', 'train')

Removed 3 NaN entries.


In [4]:
next(iter(dataloader))

((tensor([[[233, 233, 233,  ...,  60,  68,  72],
           [233, 233, 233,  ...,  68,  71,  75],
           [233, 233, 233,  ...,  51,  76,  72],
           ...,
           [212, 215, 218,  ..., 226, 230, 232],
           [216, 218, 219,  ..., 231, 232, 228],
           [217, 219, 219,  ..., 230, 233, 231]],
  
          [[255, 255, 255,  ...,  59,  66,  71],
           [255, 255, 255,  ...,  63,  68,  73],
           [255, 255, 255,  ...,  41,  66,  64],
           ...,
           [196, 198, 201,  ..., 200, 204, 208],
           [199, 201, 202,  ..., 206, 207, 206],
           [200, 202, 202,  ..., 205, 211, 209]],
  
          [[253, 253, 253,  ...,  67,  79,  85],
           [253, 253, 253,  ...,  70,  79,  86],
           [253, 253, 253,  ...,  49,  77,  77],
           ...,
           [183, 188, 194,  ..., 201, 205, 208],
           [189, 191, 195,  ..., 209, 210, 208],
           [190, 194, 195,  ..., 208, 213, 211]]], dtype=torch.uint8),
  tensor([[[108, 108, 108,  ..., 123, 12

In [7]:
ds = dataset.get_dataset('train', 'detection')

Removed 3 NaN entries.


In [8]:
ds[0]

(tensor([[[255, 255, 255,  ..., 196, 192, 191],
          [255, 255, 255,  ..., 185, 197, 193],
          [255, 255, 255,  ..., 204, 195, 203],
          ...,
          [ 46,  41,  36,  ...,  65,  66,  66],
          [ 41,  36,  32,  ...,  64,  66,  67],
          [ 34,  30,  31,  ...,  64,  68,  68]],
 
         [[255, 255, 255,  ..., 184, 178, 174],
          [255, 255, 255,  ..., 173, 182, 178],
          [255, 255, 255,  ..., 192, 180, 189],
          ...,
          [ 57,  52,  44,  ...,  68,  67,  67],
          [ 52,  47,  40,  ...,  67,  67,  66],
          [ 45,  41,  39,  ...,  67,  67,  67]],
 
         [[255, 255, 255,  ..., 170, 169, 167],
          [255, 255, 255,  ..., 159, 175, 173],
          [255, 255, 255,  ..., 180, 175, 188],
          ...,
          [ 75,  70,  63,  ..., 101,  98,  98],
          [ 72,  67,  59,  ..., 100,  98,  98],
          [ 65,  61,  58,  ..., 100,  99,  99]]], dtype=torch.uint8),
 {'boxes': tensor([[ 273.4149,  412.8664,   73.2516,   56.0371]

In [2]:
alias = Alias([
    Generic("{}", DataTypes.IMAGE_NAME),
    Generic("{}_{}", DataTypes.CLASS_NAME, DataTypes.GENERIC)
])
root = '/Users/atong/Documents/Datasets/OxfordPets'
form = {
    Static("annotations"): {
        Generic("{}.txt", DataTypes.IMAGE_SET): TXTFile(
            Generic(
                "{} {} {} {}", alias, DataTypes.GENERIC, DataTypes.GENERIC, DataTypes.CLASS_ID
            ),
            ignore_type = '#'
        )
    },
    Static("images"): {
        Generic("{}.jpg", alias): Image()
    },
    Static("class.txt"): TXTFile(
        Generic("{} {}", DataTypes.CLASS_NAME, DataTypes.CLASS_ID)
    )
}
dataset = CVData(root, form)


In [3]:
s = dataset.get_dataset('test', 'classification')

In [4]:
s[0]

(tensor([[[ 82,  80,  82,  ..., 127, 126, 126],
          [ 79,  74,  77,  ..., 127, 122, 123],
          [ 79,  80,  83,  ..., 126, 123, 119],
          ...,
          [158, 176, 210,  ..., 208, 209, 210],
          [152, 181, 199,  ..., 208, 209, 209],
          [156, 177, 188,  ..., 209, 210, 207]],
 
         [[ 77,  75,  77,  ..., 128, 127, 127],
          [ 74,  69,  72,  ..., 128, 123, 124],
          [ 75,  76,  79,  ..., 127, 124, 120],
          ...,
          [156, 175, 208,  ..., 239, 240, 240],
          [150, 177, 195,  ..., 239, 240, 239],
          [151, 171, 184,  ..., 240, 241, 237]],
 
         [[ 73,  71,  73,  ..., 123, 121, 121],
          [ 70,  63,  66,  ..., 123, 117, 118],
          [ 66,  67,  70,  ..., 121, 118, 114],
          ...,
          [133, 144, 167,  ..., 195, 198, 202],
          [127, 148, 157,  ..., 195, 198, 201],
          [131, 145, 149,  ..., 196, 200, 199]]], dtype=torch.uint8),
 10)